MODEL:
  TYPE: ResNet18_Branches
  NAME: resnetbranches_nomul_nolsl_identical_path_ens_valmax_train_partial_standaug_dist_standaug_lossmin_train_partial0.5
  DROP_PATH_RATE: 0.5
  CLASSIFIER: 'linear'
TRAIN:
  OPTIMIZER:
    NAME: 'sgd'
  LR_SCHEDULER:
    NAME: 'cosine'
  BASE_LR: 0.001  
  WEIGHT_DECAY: 5e-4
  MIN_LR: 1e-4
  EPOCHS: 60
  CLIP_GRAD: 20.0    #waited to make sure
  PRE_EPOCH: 0
  WARMUP_EPOCHS: 0    
  WARMUP_LR: 1.25e-4
  T: 5.0
  MODEL_SELECTION: 'valacc' #valacc
DATA :
  DATASET: 'SpecialDomainNet'
  SPLIT: 'special'  #not work
  SPLIT_RATE : 0.9  #not work
  BATCH_SIZE: 16
  # NUM_WORKERS : 1
AUG: 
  AUTO_AUGMENT: 'standard' 
  


