MODEL:
  TYPE: ResNet50
  NAME: resnet50_real_no_mul
  ENSEM_TYPE: ResNet50_Branches
  ENSEM_NAME: resnet50_real_no_mul
  CLASSIFIER: 'linear'
  DROP_PATH_RATE: 0.5
TRAIN:
  OPTIMIZER:
    NAME: 'sgd'
  LR_SCHEDULER:
    NAME: 'cosine'
  BASE_LR: 0.001
  WEIGHT_DECAY: 5e-4
  MIN_LR: 1e-4
  EPOCHS: 60
  CLIP_GRAD: 20.0    #waited to make sure
  T: 5.0
  ACCUMULATION_STEPS: 1
  RANDOM_SAMPLER: True
  MODEL_SELECTION: 'valacc' #valacc
DATA :
  DATASET: 'SpecialDomainNet'
  SPLIT: 'special'  #not work
  SPLIT_RATE : 0.9  #not work
  BATCH_SIZE: 16
DISTILL:
  GAMMA: 0.5
  IDENTICAL_LOGIT: True
AUG: 
  AUTO_AUGMENT: 'standard'
  


